run:
	cp .bashrc ~/.bashrc
	cp .bash_profile ~/.bash_profile
	cp .bash_aliases ~/.bash_aliases
	cp .gitconfig ~/.gitconfig
	mkdir ~/.ssh
	cp ./.ssh/config ~/.ssh/config
	cp .vimrc ~/.vimrc
	cp .tmux.conf ~/.tmux.conf
	
setup-aws:
	sudo apt install awscli